#include "lvgl.h"

// autogenerated, do not modify!

#if defined(NERDOCTAXEGAMMA)
#include "./NerdOctaxeGamma/ui_img_initscreen2_png.c"
#include "./NerdOctaxeGamma/ui_img_miningscreen2_png.c"
#include "./NerdOctaxeGamma/ui_img_portalscreen_png.c"
#include "./NerdOctaxeGamma/ui_img_btcscreen_png.c"
#include "./NerdOctaxeGamma/ui_img_settingsscreen_png.c"
#include "./NerdOctaxeGamma/ui_img_splashscreen2_png.c"
#include "./NerdOctaxeGamma/ui_img_globalStats_png.c"
#endif

#if defined(NERDQAXEPLUS)
#include "./NerdQaxePlus/ui_img_initscreen2_png.c"
#include "./NerdQaxePlus/ui_img_miningscreen2_png.c"
#include "./NerdQaxePlus/ui_img_portalscreen_png.c"
#include "./NerdQaxePlus/ui_img_btcscreen_png.c"
#include "./NerdQaxePlus/ui_img_settingsscreen_png.c"
#include "./NerdQaxePlus/ui_img_splashscreen2_png.c"
#include "./NerdQaxePlus/ui_img_globalStats_png.c"
#endif

#if defined(NERDEKO)
#include "./NerdEko/ui_img_initscreen2_png.c"
#include "./NerdEko/ui_img_miningscreen2_png.c"
#include "./NerdEko/ui_img_portalscreen_png.c"
#include "./NerdEko/ui_img_btcscreen_png.c"
#include "./NerdEko/ui_img_settingsscreen_png.c"
#include "./NerdEko/ui_img_splashscreen2_png.c"
#include "./NerdEko/ui_img_globalStats_png.c"
#endif

#if defined(NERDQAXEPLUS2)
#include "./NerdQaxePlus2/ui_img_initscreen2_png.c"
#include "./NerdQaxePlus2/ui_img_miningscreen2_png.c"
#include "./NerdQaxePlus2/ui_img_portalscreen_png.c"
#include "./NerdQaxePlus2/ui_img_btcscreen_png.c"
#include "./NerdQaxePlus2/ui_img_settingsscreen_png.c"
#include "./NerdQaxePlus2/ui_img_splashscreen2_png.c"
#include "./NerdQaxePlus2/ui_img_globalStats_png.c"
#endif

#if defined(NERDAXE)
#include "./NerdAxe/ui_img_initscreen2_png.c"
#include "./NerdAxe/ui_img_miningscreen2_png.c"
#include "./NerdAxe/ui_img_portalscreen_png.c"
#include "./NerdAxe/ui_img_btcscreen_png.c"
#include "./NerdAxe/ui_img_settingsscreen_png.c"
#include "./NerdAxe/ui_img_splashscreen2_png.c"
#include "./NerdAxe/ui_img_globalStats_png.c"
#endif

#if defined(NERDAXEGAMMA)
#include "./NerdAxeGamma/ui_img_initscreen2_png.c"
#include "./NerdAxeGamma/ui_img_miningscreen2_png.c"
#include "./NerdAxeGamma/ui_img_portalscreen_png.c"
#include "./NerdAxeGamma/ui_img_btcscreen_png.c"
#include "./NerdAxeGamma/ui_img_settingsscreen_png.c"
#include "./NerdAxeGamma/ui_img_splashscreen2_png.c"
#include "./NerdAxeGamma/ui_img_globalStats_png.c"
#endif

#if defined(NERDQX)
#include "./NerdQX/ui_img_initscreen2_png.c"
#include "./NerdQX/ui_img_miningscreen2_png.c"
#include "./NerdQX/ui_img_portalscreen_png.c"
#include "./NerdQX/ui_img_btcscreen_png.c"
#include "./NerdQX/ui_img_settingsscreen_png.c"
#include "./NerdQX/ui_img_splashscreen2_png.c"
#include "./NerdQX/ui_img_globalStats_png.c"
#endif

#if defined(NERDOCTAXEPLUS)
#include "./NerdOctaxePlus/ui_img_initscreen2_png.c"
#include "./NerdOctaxePlus/ui_img_miningscreen2_png.c"
#include "./NerdOctaxePlus/ui_img_portalscreen_png.c"
#include "./NerdOctaxePlus/ui_img_btcscreen_png.c"
#include "./NerdOctaxePlus/ui_img_settingsscreen_png.c"
#include "./NerdOctaxePlus/ui_img_splashscreen2_png.c"
#include "./NerdOctaxePlus/ui_img_globalStats_png.c"
#endif

#if defined(Q1370) || defined(Q1373)
#include "./Generic/ui_img_initscreen2_png.c"
#include "./Generic/ui_img_miningscreen2_png.c"
#include "./Generic/ui_img_portalscreen_png.c"
#include "./Generic/ui_img_btcscreen_png.c"
#include "./Generic/ui_img_settingsscreen_png.c"
#include "./Generic/ui_img_splashscreen2_png.c"
#include "./Generic/ui_img_globalStats_png.c"
#endif

#if defined(NERDHAXEGAMMA)
#include "./NerdHaxeGamma/ui_img_initscreen2_png.c"
#include "./NerdHaxeGamma/ui_img_miningscreen2_png.c"
#include "./NerdHaxeGamma/ui_img_portalscreen_png.c"
#include "./NerdHaxeGamma/ui_img_btcscreen_png.c"
#include "./NerdHaxeGamma/ui_img_settingsscreen_png.c"
#include "./NerdHaxeGamma/ui_img_splashscreen2_png.c"
#include "./NerdHaxeGamma/ui_img_globalStats_png.c"
#endif

#if defined(BV001)
#include "./BV001/ui_img_initscreen2_png.c"
#include "./BV001/ui_img_miningscreen2_png.c"
#include "./BV001/ui_img_portalscreen_png.c"
#include "./BV001/ui_img_btcscreen_png.c"
#include "./BV001/ui_img_settingsscreen_png.c"
#include "./BV001/ui_img_splashscreen2_png.c"
#include "./BV001/ui_img_globalStats_png.c"
#endif

#if defined(BV002)
#include "./BV002/ui_img_initscreen2_png.c"
#include "./BV002/ui_img_miningscreen2_png.c"
#include "./BV002/ui_img_portalscreen_png.c"
#include "./BV002/ui_img_btcscreen_png.c"
#include "./BV002/ui_img_settingsscreen_png.c"
#include "./BV002/ui_img_splashscreen2_png.c"
#include "./BV002/ui_img_globalStats_png.c"
#endif

#if defined(BV003)
#include "./BV003/ui_img_initscreen2_png.c"
#include "./BV003/ui_img_miningscreen2_png.c"
#include "./BV003/ui_img_portalscreen_png.c"
#include "./BV003/ui_img_btcscreen_png.c"
#include "./BV003/ui_img_settingsscreen_png.c"
#include "./BV003/ui_img_splashscreen2_png.c"
#include "./BV003/ui_img_globalStats_png.c"
#endif
